### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yuta-nakashima** [yuta-nakashima/furima-32029#10]
自身のフリマアプリのURL 
https://furima-32029.herokuapp.com/

Basic認証のIDとパスワード 
ID: admin  PW:2222

出品者用のメールアドレスとパスワード 
Email: 11@11  PW:q12345

購入者用のメールアドレスとパスワード
Email: 22@22  PW:q12345

購入用カードの番号・期限・セキュリティコード
番号: 4242424242424242
期限: 2/23
セキュリティコード: 123

**Comment by tcamp1234** [comment]
yuta-nakashima さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◎商品編集機能
必要な情報を適切に入力しても、商品情報（商品画像・商品名・商品の状態など）を変更できません。
（商品画像に関して、編集を行なっても出品時の商品画像になってしまいます）

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yuta-nakashima** [comment]
大変失礼しました。
editのimage部分の表記が抜けており、反映できておりませんでした。
挙動確認を行いましたので、再度ご確認をよろしくお願いいたします。

**Comment by tcamp1234** [comment]
yuta-nakashima さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
